### ISSUE TITLE
Research best practice with regard to trailing slash

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#179]
Let's research the best practice with regard to trailing slashes. If we find out that it doesn't matter, can we enforce non-trailing-slash for prettiness sake? 

The redirect can also happen client side. I noticed for some website if I add a trailing slash, Chrome removes it before requesting the website.

**Comment by wholesomedev** [comment]
I thought more about this and I think for the legacy website we should consistently serve the version **with** the `/` because that's the expected version from the website. If we move to the non-`/` version that means we'll have to modify our WordPress, which is not something we want to do.

So I guess for now if there really is no difference between `/` and non-`/` in terms of SEO, we should not bother with this. And for the new website we should consistently serve the non-`/` version.

**Comment by forabi** [comment]
> If we move to the non-/ version that means we'll have to modify our WordPress, which is not something we want to do.

We do not actually need to modify WordPress. The canoncial URL is the one with the trailing slash (you can http://live.hollowverse.com/tom-hanks). What we do now is that when the user visits the URL without a trailing slash, we add the slash to the end of the URL _on the server_ _before we forward the request to WP_. That way, we save the user one redirection request and the URL does not change regardless of whether it has a trailing slash or not.

Instead of what we are doing now (adding the slash on the server), we could also redirect the user again to the URL with a trailing slash _also before we forward the URL to WP_. In that case, the user will always get the URL with a trailing slash.

> So I guess for now if there really is no difference between / and non-/ in terms of SEO, we should not bother with this. And for the new website we should consistently serve the non-/ version.

This is actually what is going to require modifications to WP or the proxy server. If we remove the slash before the request is forwarded to WP, WP will respond with `301 Moved Permanently` and the proxy server won't follow the redirect. The user will be redirected to `live.hollowverse.com`.

I just checked Twitter, Facebook and GitHub. They all respect the original URL and do not do any redirection:

https://www.facebook.com/privacy/explanation/
https://www.facebook.com/privacy/explanation

https://github.com/hollowverse/hollowverse/issues
https://github.com/hollowverse/hollowverse/issues/

https://twitter.com/forabi
https://twitter.com/forabi/

So this matches the current behavior of our server.

**Comment by forabi** [comment]
However, [this 7-years-old post on Goolge's Webmasters Blog](https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html) suggests that it is preferable to redirect one version to the other (`/` is often used for directories, the other for files, but it is not necessary to follow this rule).

If we are going to follow this advice, I think it is easier to redirect to the one with the trailing slash. However, using a trailing slash at the end of non-directory resources is semantically incorrect. In any case, both versions are doable.

**Comment by wholesomedev** [comment]
Okay, the current behavior is acceptable then. We can keep things the way they are.
