### ISSUE TITLE
Back-end architecture: going full Firebase or nay?

### ISSUE THREAD

**Issue by deltaidea** [hollowverse-archive/hollowverse#18]
There're two options for structuring back-end business logic:

- Fully embrace Firebase infrastructure
    - Use [Firebase Fuctions](https://firebase.google.com/docs/functions/) with [HTTP triggers](https://firebase.google.com/docs/functions/) for talking with the client side.
    - Use [Firebase Hosting](https://firebase.google.com/docs/hosting/) for front-end assets. It supports URL rewrites, so we can still route everything to `index.html`.
- Host bare Node.js somewhere else with Express.js (maybe on the underlying Google Cloud Platform) and only use Firebase for storage, events, etc.

The second option doesn't lock us into the Firebase platform as badly. Otherwise there's no chance for migration, ever.

Deeper integration with the platform has its benefits too: more consistency, probably faster development, less configuration for different service providers.

@msafih, what's our path here?

**Comment by wholesomedev** [comment]
@deltaidea considering our limited resources, I think we should go with the path of least resistance, especially if it doesn't conflict with our core values: engineering and UX excellence.

Staying with Firebase seems simpler. It might lock us into their platform, but maybe if we write clean code that's easy to maintain and refactor, migrating away from Firebase might still be possible, albeit painful.

That's why I'm inclined to go with the first option.
