### ISSUE TITLE
Refactor custom global type definitions

### ISSUE THREAD

**Issue by deltaidea** [hollowverse-archive/hollowverse#25]
- [ ] Use [`@types/facebook-js-sdk`](https://www.npmjs.com/package/@types/facebook-js-sdk) instead of custom definitions in `global.d.ts`
- [x] ~Merge `typeDefinitions.ts` into `global.d.ts`~

**Comment by wholesomedev** [comment]
> Use [`@types/facebook-js-sdk`](https://www.npmjs.com/package/@types/facebook-js-sdk) instead of custom definitions in `global.d.ts`

I remember trying `@types/facebook-js-sdk`. It wasn't good, that's why I decided to have my own definition. Maybe we can use `@types/facebook.js-sdk` and contribute improvements to it, if you think that's a better approach.

> Merge `typeDefinitions.ts` into `global.d.ts`

The reason I have them separated is because in TypeScript we can either have a "module" file or a "global" file. Once we use the keywords `import` or `export` in a file, it loses its global status. I  assumed that global variables have to have global type definitions. If that's not the case, I guess we can move `global.d.ts` type definitions to `typeDefitions.ts` and import them where we need them.

**Comment by deltaidea** [comment]
Disregard the second point, I didn't know that.

**Comment by wholesomedev** [comment]
But if it is possible to have definitions of global variables be in a module, I think that would be better 😄

**Comment by wholesomedev** [comment]
This is not as relevant anymore
