### ISSUE TITLE
Create automatic performance tracking reports

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#251]
We have manually used different services to check the performance of our app in terms of security, speed, and other metrics. 

We need to automate these checks and generate public reports so that we don't fall behind on those metrics.

**Comment by forabi** [comment]
> We need to automate these checks and generate public reports so that we don't fall behind on those metrics.

I'm very interested in integrating [Lighthouse CI](https://github.com/ebidel/lighthouse-ci) into our CI pipeline, but in order to have realistic data, we would need to deploy the app to a temporary instance that is as close as possible to the production instances, but it might be costly to allow every PR to deploy an instance.

**Comment by wholesomedev** [comment]
@forabi Can't the PR deploy the instance, run the Lighthouse tests, then delete the instance?

**Comment by forabi** [comment]
> Can't the PR deploy the instance, run the Lighthouse tests, then delete the instance?

That's possible, although I'd like to find some way to control who can deploy from PRs (if at all possible).

**Comment by wholesomedev** [comment]
Hmm, good point. I guess this is not meant for publicly maintained websites?

**Comment by forabi** [comment]
I think it's meant for SPAs that can be easily deployed to services
like now and GitHub Pages

**Comment by forabi** [comment]
I've thought about this, I think we have the following options:

1. Keep a `t2.nano` instance always up, and use it for all PRs. This might be a better trade-off than creating and destroying an EB environment (including a load balancer) on _every push_ to _every PR_. The PR build would be accessed via Release Manager just like we do for internal branches. This does not require any changes to release manager. We can simply run Lighthouse against `https://hollowverse/?branch=pr-245` for example.
2. Create and destroy a new EB instance on every push to every PR. This is tricky to do on CI because as far as I can tell not all the configuration options that we use for production/test branches are available via the AWS EB CLI. This requires more investigation.
3. Create and destory a new instance for PRs from authorized contributors, we could query the GitHub API on CI to check if the PR author is in the authorized list. This of course means that PRs from other contributors won't be checked with Lighthouse. As an alternative, we can configure our deployment script to do blue/green deployments, i.e. use a staging server to run Lighthouse and only continue deployment if Lighthouse tests pass.

I think option 1 is the simplest, but it has one caveat: if commits are pushed to two different PRs at the same time, one PR could fail because a deployment is already in progress on Elastic Beanstalk, in that case the CI job would need to be restarted.

**Comment by wholesomedev** [comment]
What about **not** using Lighthouse CI, instead run Lighthouse against the live website periodically, like daily?

Regarding the options you've outlined above: even No. 1 would require authorizing the PR author before deploying. And the caveat you've mentioned adds some complexity in behavior and expectations. So it doesn't feel like a good long-term solution.

**Comment by forabi** [comment]
That sounds fine. I think we need to test the following aspects:

* Performance (load time + runtime, first and repeat view)
* Security
* SEO
* W3C-valid HTML and CSS
* Accessibility
* Best practices

Looks like we can use a [scheduled AWS Lambda function](https://docs.aws.amazon.com/lambda/latest/dg/with-scheduled-events.html) for this. I think it should work like this:

1. Function is triggered
2. Function runs a set of "reporters", some of the services that we could utilize include:
    * [WebPageTest](https://www.webpagetest.org) (has an API)
    * [Lighthouse](https://github.com/GoogleChrome/lighthouse) (best if we do this on real devices and connections, via WebPageTest)
    * [Sonarwahl](https://sonarwhal.com)
    * [securityheaders.io](https://securityheaders.io) (sort of has an API, [via HTTP headers](https://github.com/securityheaders/securityheaders-bugs/issues/17#issuecomment-246103211))
     * Custom log events in SumoLogic (for things like navigation timing data, page load failures...)
3. Each reporter knows how to talk to the respective service/API/package, parse the results and provide them to the lambda function
4. The lambda functions stores the reports in S3
5. On subsequent runs, the lambda function repeats the previous steps and additionally fetches the most recent reports, asks the reporters to compare the two sets of reports to see if we have regressed in some reports.
6. In case of regressions, the lambda function posts an issue on GitHub to let us know of the problems.

We can also build a web app hosted on GitHub pages that can consume, visualize and compare these reports.

**Comment by wholesomedev** [comment]
@forabi This sounds good. Though one area that would be tricky to implement is the diffing between the reports. An easier approach could be to create a reports folder in our repo, and have the Lambda send a PR with new reports every day (or only if there have been changes to `master` since last day the reports were PRed).

The reports could come in some text format or images.

**Comment by forabi** [comment]
I was thinking we should just compare the scores

wholesomedev <notifications@github.com> schrieb am Fr., 9. Feb. 2018, 3:17
vorm.:

**Comment by wholesomedev** [comment]
I’m okay with either approach. You can try both out and see what makes sense

**Comment by wholesomedev** [comment]
We can also look into whether it makes sense to create a health check report of our AWS infra. Though, obviously, such report is not a substitute for realtime alerts if something goes completely wrong...

**Comment by forabi** [comment]
Looks like Lighthouse allows us to add custom audits https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit

That's nice!

**Comment by forabi** [comment]
This is partially done (turns out Sonarwahl does not have an API). We still need to add health checks for AWS.
