### ISSUE TITLE
Development server doesn't handle some URLs (e.g. `/`, `/privacy-policy`)

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#324]
While developing, it's not possible to load `/` or `/privacy-policy` directly.

**Comment by forabi** [comment]
This is because these pages have a matching page with the same path on the old website. The development server is started from `appServer.dev.ts`, which does not proxy requests to the old website. `mainServer.ts` is what handles proxying. We need to override this behavior in development environment so that the middleware returned from `createServerRenderMiddleware` does not forward requests, and instead forces all pages to be rendered by the new app. This may make it less convenient to debug the proxying logic in development though.
