### ISSUE TITLE
Consider using per-resource AWS credentials for our different CI-enabled repos

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#359]
To improve our security, it might be a good idea to use different AWS users on CI to deploy each one of the resources we currently have (`perf-monitor`, `lambda-assign-env`, `crop-face`... etc.). Each of the CI users should only have the permissions required to write to the specified resource. For example, `crop-face` CI user should not have access to `lambda-assign-env`. Not all permissions on AWS can be restricted per resource, but [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege) is still a good practice to follow security-wise.

**Comment by wholesomedev** [comment]
Agreed.

On an unrelated topic: `perf-monitor` (noun), `lambda-assign-env` (verb), `crop-face` (verb). We should probably standardize on either noun or verb. Since functions are generally given verbs as names, and these Lambdas are functions, it might be good to standardize around verbs...I guess `perf-monitor` can be considered either noun or verb, so I guess we don't have an issue here...okay, please carry on... 😄

**Comment by forabi** [comment]
`perf-monitor` does not sound like a verb to me :rofl: Maybe `monitor-perf` or `track-perf`?

**Comment by wholesomedev** [comment]
`track-perf` sounds good!

**Comment by forabi** [comment]
I don't think this is relevant considering that we are now delegating permission management to Serverless.
