### ISSUE TITLE
Should we use `npm-check`?

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#377]
Should we use `npm-check` to verify that the packages that we have installed are actually being used?

https://github.com/dylang/npm-check

**Comment by forabi** [comment]
I actually gave it a try a few months back, but the problem is that it does
not play well with Webpack imports. It only works for standard Node.js
imports. Webpack can resolve a lot more styles of imports like
"src/components/App" instead of "../../src/components/App" and
"!!file-loader!path/to/file" etc.

I don't think it would be very helpful for our codebase. Webpack already
only includes imported modules in the browser bundles and unneeded packages
do not cause a runtime performance hit on Node.js so the only issue with
unneeded imports is the increased size of the server-side package.

**Comment by forabi** [comment]
I'm not sure if it's the same package I tried but it had a similar
functionality

**Comment by forabi** [comment]
The tool I tried is https://github.com/depcheck/depcheck

To be more clear, the issues I encountered with the imports were due to `depcheck` thinking `src/components/App/App.tsx` belongs to a package called `src`. I don't think `npm-check` will work with these imports either, but I'm gonna give it a try anyway.

**Comment by forabi** [comment]
So... I tried `npm-check` and it seems that the way it works is different from `depcheck`. `depcheck` reads the imports in JS/TS files in the codebase and looks for packages matching those imports. This is why it thinks `src` is a package. `npm-check` on the other hand seems to start by looking at the packages in `package.json` and looks for one or more files requiring each listed package. This is why it _doesn't_ confuse `src` for a package.

But, it still reports too many false positives. `graphql-request` is definitely and explicitly required in `src/api/client.ts` but it thinks for some reason that it is not used. `classcat` too. `http-proxy`, `lodash`... too many to list. Is it not parsing TypeScript files? :thinking: 

Dynamic imports (e.g. `import('intersection-observer-polyfill')`) are reported as unused too. Tools like `jest`, `ts-jest`, `npm-run-all` which are not imported in code are also reported as unused.

**Comment by wholesomedev** [comment]
Okay, if you don't think adding it creates more value than not having it, we can close this issue for now until a better solutions comes along.

**Comment by forabi** [comment]
I don't think we'll find a generic tool that can recognize non-standard webpack imports. Any tool that we would want to use should be able to read and understand webpack configuration and resolve the imports exactly like webpack does.
