### ISSUE TITLE
Add documentation to `/redux` folder

### ISSUE THREAD

**Issue by deltaidea** [hollowverse-archive/hollowverse#40]
- [Todo app example with Redux](https://github.com/reactjs/redux/tree/master/examples/todomvc/src)
- [Splitting components into presentation and containers](https://vasanthk.gitbooks.io/react-bits/patterns/25.presentational-vs-container.html)

**Comment by wholesomedev** [comment]
👍

**Comment by wholesomedev** [comment]
I've had sometime to consider this, and I don't think it's a good idea to use container and presentational components. I remember reading a comment by Dan Abramov somewhere, even he doesn't think container/presentational is a good approach for all kinds of applications.

As for using a conventional Redux structure, that would create a lot of boilerplate. Alternative structures such as [Ducks](https://github.com/erikras/ducks-modular-redux) were created to deal with Redux boilerplate pain. The organization that we have right now is similar to Ducks (except instead of multiple modules, we have only one module). 

I think we should keep the organization that we have today, and deal with one of its main issues, which is that it's too clever.

I'll go ahead and add comments and documentation to our `/redux` folder to explain how it's structured and how it's intended to be used.

CC @levsthings
