### ISSUE TITLE
Should linter config packages be added to clown config?

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#417]
I was working on #342 and wanted to upgrade `typescript-eslint-parser`, but I just realized that it's no longer an explicit dependency of `hollowverse/hollowverse`. That got me wondering: why we are treating `typescript` and `tslint` differently from, say, `tslint-config-prettier`? `typescript` and `tslint` are merged by clown as dependencies of the project but the other packages are not. Should not we list `tslint-config-prettier`, `tslint-eslint-rules`... etc. in https://github.com/hollowverse/config/blob/master/clown/typescript/package.json ? Same for `stylelint-config-standard`, `stylelint-no-unsupported-browser-features`.

The problem with implicit dependencies is that there is no guarantee that they will be available at the root of `node_modules`. If package `A` depends on `C@2.0` and package `C` depends on `B@3.0`, `node_modules` will look like this:

```
A
|__node_modules
   |__C
B
|__node_modules
   |__C
```

which means if we do not list a package as a hard dependency, it may not be found by the tool that needs it.

**Comment by wholesomedev** [comment]
The reason I feel it makes sense to not include `typescript-eslint-parser` in the `package.json` for downstream repos is because `typescript-eslint-parser` is abstracted away by `@hollowverse/config/eslint/react/typescript/.eslintrc.json`.

Downstream repos shouldn't care too much about how `@hollowverse/config/eslint/react/typescript/.eslintrc.json` lints code or what plugins it uses. They just want to extend it.

That's not the case with `typescript`, `tslint`, and `eslint` CLIs themselves because these tools are called and used directly by the repos that use them.

**Comment by forabi** [comment]
I just got that feeling that implicit dependencies will come back to bite us later. We are depending on the flattening behavior of `yarn`/`npm` (which is an implementation detail) instead of the "right" way to install dependencies. I think `clown` is super helpful for composing dependencies so why not take advantage of that?

**Comment by forabi** [comment]
Resolved in recent versions of config.
