### ISSUE TITLE
Document deployment architecture

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#454]
Document deployment, such as the relationship between GitHub, Travis, Docker, Serverless, and AWS.

@forabi could you provide insight on how that stuff happens here, I can then update hollowverse/architecture?

**Comment by forabi** [comment]
* GitHub notifies Travis of new pull requests or merges
* Travis pulls the GitHub repo abd checks out the branch in question, and performs the commands in `.travis.yml` which instruct Travis to pull a Docker image, `hollowverse/build-env`, which will be used to perform all build/deployment tasks.
* Travis [runs a container](https://github.com/hollowverse/hollowverse/blob/ef166850d2007a85a99b70fc1c5f37bf6cdac1a8/.travis.yml#L5) based off of `hollowverse/build-env` with the directory of the cloned git repository mounted at `/repo` inside the container, which allows the container access to the source code. When Docker starts a container, it executes the [`CMD` instruction](https://github.com/hollowverse/build-env/blob/2db31a84529b223dc84802104d301c82735ebff3/Dockerfile#L20). That's `yarn && yarn deploy` for `hollowverse/build-env`. `deploy` is expected to be defined in `/repo/package.json` (i.e. the root of the cloned git repo).
* The `build-env` image closely matches the target deployment environment. For example, if we are targeting Lambda with Node.js 8, the `build-env` image will contain Node.js 8 and all the native runtime libraries that are expected to be available in Lambda execution environment. Additionally, the `build-env` contains some binaries and tools that are required to build some Node.js packages but are not required at runtime. Because the Lambda execution environment is pretty restricted, we try to ensure that no extraneous dependencies are available at build time, to avoid any possible runtime errors.
* `yarn deploy` will execute inside the container on CI. This command varies from repo to another in the hollowverse organization, but we follow a convention of aliasing `yarn deploy` a `babel-node deploy.js`. `deploy.js` will execute all build (and deployment) tasks.
* For PR builds, we only run the lint checks, tests and build steps. For deployment tasks we additionally perform the deployment.
* Packaging and deployments are handled by the Serverless framework. Serverless will read `serverless.yml` and build the specified functions. The frameworks is pretty extensible so the actual build steps may vary depending on the repo. For example, `serverless-webpack` hooks into the build step and runs webpack on the functions. This takes care of transpiling TypeScript and minifying the output, and packaging all the dependencies required by each function.
* Serverless will take the build package (a ZIP file) and upload it to S3, from there it creates a [CloudFormation](https://aws.amazon.com/cloudformation/) stack. CloudFormation is an AWS service that allows managing a group of resources from different AWS services. This group of services is called a stack. For example, a stack may define a CloudFront distribution, a Route 53 record, 2 Lambda functions, an API Gateway API and an S3 bucket with corresponding IAM roles and permissions to allow interactions between these resources. These resources are defined based on the contents of `serverless.yml`. CloudFormation handles any future updates to this stack. Stacks can be easily removed by running `serverless remove`. This will delete all the AWS resources defined in the stack.
* Serverless does a lot of things so naturally it requires extensive access to AWS. We have a user called `serverless-agent` in IAM and the credentials for that user are defined in Travis secure settings and passed to the `build-env` container as environment variables (specifically, `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`). Serverless expects these two variables.
