### ISSUE TITLE
Using feature flags instead of `beta`/`master`

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#467]
I think in the future, it makes more sense to use [feature flags](https://martinfowler.com/articles/feature-toggles.html) rather than `beta`/`master`

The `beta`/`master` approach has limitations. One limitation is that it's only available in h/hollowverse. What if we wanted to run experiments in other services, like h/route-request or h/api? We can't.

Using feature flags gives us more flexibility.

This is just a topic I wanted to float around. There's nothing we need to do now. We can continue to use our `beta`/`master` approach until we feel a stronger need for a better solution.

Do you have any thoughts on feature flags?

**Comment by forabi** [comment]
I know many of the big companies use feature flags. It's not difficult to implement--instead of a single `env` cookie we can set many cookies and we can have different users on different combinations of features. We just have to keep in mind that this may increase the complexity of debugging as there will be a lot of combinations.

**Comment by wholesomedev** [comment]
Yeah 💯. Feature flags could have a spaghetti effect on the codebase. They should be used with extreme caution. Good code architecture and design can help reduce the negative impact of feature flags.

 I think the article above touches on some of those issues (I will read it before we actually start using feature flags 😄).
