### ISSUE TITLE
Create admin UI to moderate submitted quotes

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#550]
We need a UI for moderators to monitor submitted quotes in order to prevent spam.

**Comment by wholesomedev** [comment]
A few thoughts on this:

* Should it be general purpose UI, not just for quotes but for all user contributed content?
* Can we make it like an email inbox where once a piece of content is decided on, it can be archived?

Somewhat related: should we also have a UI for managing users, like having the ability to ban spammers?

**Comment by forabi** [comment]
@wholesomedev I do think it should be a general purpose UI, but I also think we should focus on quote management on the first iteration.

> Can we make it like an email inbox where once a piece of content is decided on, it can be archived?

> should we also have a UI for managing users, like having the ability to ban spammers?

Good points. I think these will help guide the work on the API side. We should have some way to log what actions every moderator has taken so that we can display them in the archive. The logs would also be useful to prevent abuse from moderators as well.

**Comment by mxsntsr** [comment]
Hi guys,

Not sure if we've met before, but I'm going to design this UI, and I have several questions for you.

1. Is submission of a quote something that can be done through the web (desktop version) or on mobile devices or both?
2. I'm not familiar with the back-end UI you have (if you have it). So if you have it, then could you please share the access with me or walk me through it. Just want to understand if the moderation will be an add-on or as an independent UI. 
3. Do people need to have an account to submit a quote? If so do you have the profile UI where people have their basic info like name and perhaps an avatar?
4. Do you think we can send email notifications after the submission of a quote or the moderation is completed?
5. Are you planning to have some automatic spam recognition mechanism?
6. How do you think the moderation process is happening on the back-end? Is it one person who reviews the submissions or it can be a group of people?
7. If you're planning to ban users, then do you need to have a ban list UI where you can remove users from the ban list if by any reason conflict is resolved?

Of course, some of these questions might be too general, but I just want to understand where to start and what are we trying to achieve with this UI.

Let me know if you have any comments or questions.

I'm looking forward to hearing from you, guys :)

**Comment by forabi** [comment]
Hello @maxsnitser! Nice to meet you!

> Is submission of a quote something that can be done through the web (desktop version) or on mobile devices or both?

The majority of our users are on mobile but we do want to support both mobile and web versions.

> I'm not familiar with the back-end UI you have (if you have it). 

We do not currently have an backend UI for adminstrators.

> Do people need to have an account to submit a quote?

Yes.

> If so do you have the profile UI where people have their basic info like name and perhaps an avatar?

We have implemented user login and logout functionality, but it's currently not enabled on the website. Here's what it looks like (roughly): https://hollowverse-archive.github.io/design/ (check the hamburger menu). We do not have a profile page where users can edit their profile information currently (we may add one in the future, but that's out of the scope of this issue).

> Do you think we can send email notifications after the submission of a quote or the moderation is completed?

I'm not sure. @wholesomedev what do you think?

Please note that we only want to be able to moderate quotes after they have been submitted. There is no "pending approval" stage for quotes. Administrators can later check recently submitted quotes and remove abusive/spammy ones.

> Are you planning to have some automatic spam recognition mechanism?

I don't think we are planning to have this currently.

> Is it one person who reviews the submissions or it can be a group of people?

Technically, any administrator can review submissions.

> If you're planning to ban users, then do you need to have a ban list UI where you can remove users from the ban list if by any reason conflict is resolved?

Yeah, I think we'll need a ban list UI.

**Comment by wholesomedev** [comment]
Hi @maxsnitser!

Let me see if I can add to the answers that @forabi provided.

>Is submission of a quote something that can be done through the web (desktop version) or on mobile devices or both?

We only have a website. We don't have a mobile application. And, as @forabi said, most of our users are on mobile browsers. We don't do responsive layout. We have one layout that is optimized for mobile and is usable on desktop.

I'm thinking we should build our Admin UI to follow the same pattern. That is, mobile only design that is usable on desktop. Are you okay with that @forabi?

>Do you think we can send email notifications after the submission of a quote or the moderation is completed?

I don't think we should build that at the moment.

>How do you think the moderation process is happening on the back-end? Is it one person who reviews the submissions or it can be a group of people?

Our setup will be something like this: 

We will have a role called "administrator". A person with that role can take an action on an item. There won't be interactions between these administrators.

>If you're planning to ban users, then do you need to have a ban list UI where you can remove users from the ban list if by any reason conflict is resolved?

Yeah, we'll need a list of banned users. A simple list of email addresses might suffice here? @forabi?

>Of course, some of these questions might be too general, but I just want to understand where to start and what are we trying to achieve with this UI

👍

**Comment by forabi** [comment]
> That is, mobile only design that is usable on desktop. Are you okay with that @forabi?

Yeah sure :+1:

**Comment by mxsntsr** [comment]
Hi guys,

Thanks for the feedback. I'll be working on the user flow and some basic prototype as the first draft. Which will be as the first iteration that will be forwarded with a couple more, I believe, until we reach the point of having a User Experience that we need. Probably, I'll ask more questions during the process. So, anyway, I'll be keeping you updated.

**Comment by mxsntsr** [comment]
Hey guys,

  I worked on the UI for Quotes moderation here is my update:  

First of all, I created User flows for Quote Submission. Not sure if you need it, but at this stage, it’s more for me to understand how everything will work together. It’s in one PDF together with Quote Moderation. The flow that I’m currently working on. It’s really basic. 

You can check those here https://www.dropbox.com/s/5p05901tpvu9l6c/quotes-user-flow-v0.1.pdf?dl=0 and let me know if you have any comments on this.

  I made a prototype that consists of B&W wireframes that are linked with each other. You can click around and interact with it. Basically, it starts with the left menu. So if you’re an admin user, you’ll see appropriate menu items for Quotes, Muted Accounts, or you can Switch back from Admin panel to Hollowverse main area.

I’ve designed cards for each quote where you can see a name of a notable person, quote preview, and date/time when it was left. So from here, you have several choices:
- You can simply tap on the quote card and go to a screen with the full quote text and info about a user who submitted it.
- You can use quick actions to Accept/Decline/Mute user
- You can use filters change the view from grouping by date to grouping by notable persons, switch show/hide Accepted and Declined quotes.

On the Quote screen, you can Accept/Decline quote and Mute the person who submitted it.

On the screen, with Muted users you can see a list of people with names and emails. And you simply can tick some of them to unmute.

You can find this prototype here:  https://invis.io/7RNLOUICEPU (try to copy and paste the URL if it's not opening right from here)   Let me know if you want to collaborate in it. I can send you invitations to your emails, guys. So you can leave comments right on screens. I’ll understand if you want to hold all communications here. So it’s up to you.

Please check everything and let me know if you have any questions. I can do a couple more rounds until we reach the experience that you think will work well for users.

**Comment by wholesomedev** [comment]
Thank you @maxsnitser, this looks great!

Here's my feedback:

* With regard to the quotes submission flow, the flowchart is a little different from what we have implemented for user registration and login. But that's okay for now since it is not an integral piece to the Admin UI itself
* The Quote Moderation flowchart looks good 👍 
* With regard to the quote moderation page:
  * At this stage, I don't think we need a Quote Details page. So if we eliminate the Details page then all the information about the quote and actions should be available from the main Moderation page itself
  * Thank you for capturing the information that goes into a contributed quote. I think you covered most elements but there might be a few elements missing, such as the date on which the quote was published by the NP and the source of the quote.

    Instead of trying to come up with a design just for quote moderation, can we come up with a design for the moderation of any piece of content? For example, the raw data that will be moderated will be:

    |name of data|value of data|
    |-|-|
    |Content type|Quote|
    |NP name|Tom Hanks|
    |Quote|Deep statement about the order of the universe|
    |Submission date|11/11/2018|
    |Submission by|Chris Cruz|
    |Etc|Etc|

    Can we come up with a design that is versatile enough to display this data, even if we add or remove rows from this table? That way we have more flexibility.
  * I don't think sorting should be configurable. It should just default to chronological order with the oldest first, like an email inbox
  * Good call on the "Show accepted"/"Show declined" toggles. We'll probably need those.
  * With regard to the action buttons, I was thinking maybe we should not tuck them inside a menu and instead bring them outside to make them more accessible. But I'm not sure that's a good idea because I don't think we should optimize for speed in this view. The moderator is expected to examine the content of the contribution not quickly click through the list
* With regard to the muted accounts page:
  * I think we should also come up with a generic flexible design for this page that would allow us to add and remove content
  * should we call it "User moderation" page?
  * I think we would need the ability to search for users
* I see that you didn't add pagination to the views. I think that's good. There's no need for pagination in these views

@forabi what do you think of my and @maxsnitser posts above?

**Comment by forabi** [comment]
Hi @wholesomedev @maxsnitser! The wireframes look great!

With regard to the quote submission flow, in addition to what @wholesomedev pointed out, I remember that following discussions with @wholesomedev on Discord, we concluded that submitted quotes should be immediately published to the website, without having to go through an approval stage. Administrators can later review the recently submitted quotes and remove inappropriate ones. So I'm not sure if the success message "submitted, waiting for moderation" is accurate.

The quote moderation flow looks fine to me, but again I'm not sure if we should use the word "Accept" and "Decline" as these quotes are already published. Maybe "Done" and "Remove" are more suitable?

I don't have any notes on the quotes moderation UX besides @wholesomedev's feedback.

**Comment by mxsntsr** [comment]
Hi guys,

Sorry for the delay. Thank you very much for the detailed feedback. I'll be working on the updates Tomorrow.

I'll combine Quotes and Quote Details into one screen and work on the generalization of this screen. Also will work on the vocabulary. Since @forabi mentioned that you don't have such thing as submission of quotes.

I just have one question for now regarding "Users moderation". What kind of content do you expect to have there? We have name and email as for now. Do you think we can add user photo, and some info about users? Perhaps maybe a user page with more details?

Please let me know.

**Comment by wholesomedev** [comment]
@maxsnitser 

We have quote submissions and we display the submitted quotes instantly. However, all submitted quotes will appear in the moderation queue to be either confirmed or removed by a moderator.

I would say don't worry about the vocabulary too much. We can tweak those on our end as things evolve.

In the User Moderation page (which should probably be called User Management to better describe its purpose), we may want the name of the user, their email address, their Facebook ID, and maybe their profile image (not sure about this one). If we can come up with a generic design that's not specific to the exact fields that we want to show, that would be better I think.

We may need a user details page at some point in the future, but not at this time.

**Comment by mxsntsr** [comment]
Hi guys,

I've made updates to Quotes. So right now you have everything on one screen, and it's not necessary to go to another screen for details. I've extended cards and even placed subtle buttons below each card for admin to Confirm or Delete quotes. Also, you can find there such data as Source, Submission date, Who submitted, and his/her photo. I've removed Sort settings and left just 2 toggles to show/hide confirmed and deleted quotes. 

One important note regarding interaction/transitions: If you click on one of the buttons, Confirm/Delete on the Quote card then you can see feedback right in the card. I can't show you the whole interaction within this InVision project, but basically, the idea is to show feedback (i.e., it's confirmed) and then this card will disappear from the screen to leave more room for other cards quotes that weren't reviewed yet. 

I've re-designed the screen for User Management. Now it has cards for each user that are consists of User pic, Name, Email, Facebook id and 3 dots for actions like Ban the account. Also, you can see there navigation tabs that allow you to see all your user base or switch to banned accounts and unmute them from there. You can try clicking on tabs to see what I mean.

You can find all the updates in the same project I shared earlier. Here is the link again https://invis.io/7RNLOUICEPU 

Please let me know what you think.

**Comment by forabi** [comment]
Hi @maxsnitser! The changes look good to me and the entire UX is just great!

**Comment by wholesomedev** [comment]
@maxsnitser Thanks a lot for addressing the feedback!

@forabi if you're okay with the latest changes from Max, we can go ahead with those. 

I'm wondering though if we'll have the flexibility to remove and add new elements with the current design.

**Comment by mxsntsr** [comment]
Hey guys,

Thank you so much for the feedback.

Do you want me to proceed with the design? I mean how it looks and feels (i.e. colors, fonts, etc.)

Yes @wholesomedev , the cards concept is pretty much flexible. So you can change it on your own by adding and removing data, you can mix different cards on one screen if needed. But if you need any specifics you can send me a request and I'll work on more card views/states.

Let me know.

**Comment by forabi** [comment]
> I'm wondering though if we'll have the flexibility to remove and add new elements with the current design.

@wholesomedev Can you elaborate? The way I see it is that we can add any type of data to the user cards. For the quote management section, I think what would work better for desktop is a tabular layout where we can add more data as columns, but that wouldn't look great on mobile. Listing data in rows would work better and that's what the cards allow us to do.

**Comment by forabi** [comment]
> Do you want me to proceed with the design? I mean how it looks and feels (i.e. colors, fonts, etc.)

@maxsnitser I don't think we need a full design currently.

**Comment by wholesomedev** [comment]
@forabi 

>Can you elaborate?

When I asked for a flexible layout, I meant a flexible layout for the content inside the card (not a flexible layout for the container of the cards). For example, say we wanted to add **user comment** to the Quote card, where would we put the **user comment** in the current design? (I'm not saying we should add user comments now, this is just an example)

>I think what would work better for desktop is a tabular layout 

Yes, but we've decided that we'll do mobile-only through out user facing and admin UIs

**Comment by forabi** [comment]
> For example, say we wanted to add user comment to the Quote card, where would we put the user comment in the current design? (I'm not saying we should add user comments now, this is just an example)

Yeah, I see your point. I'm out of ideas here. @maxsnitser what do you think of this particular example?

Another thing I'd like to change in the current UX is the drawer that shows up when tapping on the hamburger menu. I think it would be better if we update the wireframes to have the links to user and quote management listed in the regular menu which we currently have on the live website (Max, you can check it out on https://hollowverse.com/Tom_Hanks)

**Comment by wholesomedev** [comment]
>Another thing I'd like to change in the current UX is the drawer that shows up when tapping on the hamburger menu. I think it would be better if we update the wireframes to have the links to user and quote management listed in the regular menu which we currently have on the live website (Max, you can check it out on https://hollowverse.com/Tom_Hanks)

Yeah, my assumption was that this menu is the concept. We can use the current menu that we have for the implementation

**Comment by forabi** [comment]
> Yeah, my assumption was that this menu is the concept. We can use the current menu that we have for the implementation

Yeah, my thoughts too. Updating the wireframes is not a priority, we can adjust things in the actual implementation.

I think we can now start working on the implementation.

**Comment by mxsntsr** [comment]
Hey @wholesomedev and @forabi 

> When I asked for a flexible layout, I meant a flexible layout for the content inside the card (not a flexible layout for the container of the cards). For example, say we wanted to add user comment to the Quote card, where would we put the user comment in the current design? (I'm not saying we should add user comments now, this is just an example)

I think it should be a different card type for cases like this. It's not possible to create a card universal for every case possible. Let's take as an example the card design I created for quotes. You can see 2 action buttons at the bottom of each card. So if you want to have comments then somehow the comments section shouldn't be mixing with these buttons. Otherwise, it will be a bad UX. So probably you can add a link in the card before these buttons and a button that opens up the comments area by expanding this card. Please check this screenshot as an example: https://cl.ly/e96bca2a71e5

**Comment by mxsntsr** [comment]
> Another thing I'd like to change in the current UX is the drawer that shows up when tapping on the hamburger menu. I think it would be better if we update the wireframes to have the links to user and quote management listed in the regular menu which we currently have on the live website (Max, you can check it out on https://hollowverse.com/Tom_Hanks)

Ok, yes. The only problem I see here is that it appears randomly and closing a part of menu (hamburger) button (see the screenshot https://cl.ly/6c3020de3553 ). I'd rather do it somewhat like this https://cl.ly/f409c783aab5

Let me know what you think.

**Comment by wholesomedev** [comment]
@maxsnitser 

>I think it should be a different card type for cases like this. It's not possible to create a card universal for every case possible. Let's take as an example the card design I created for quotes. You can see 2 action buttons at the bottom of each card. So if you want to have comments then somehow the comments section shouldn't be mixing with these buttons. Otherwise, it will be a bad UX. So probably you can add a link in the card before these buttons and a button that opens up the comments area by expanding this card. Please check this screenshot as an example: https://cl.ly/e96bca2a71e5

By **user comment** I meant a single user comment. We have a hypothetical use case where the user who contributes a quote can add his or her comment with the quote. This is separate from the other user comments that appear below the quote.

Here's another example: say we want to add the location of the Notable Person when they made the quote. Where would we show the location in the card? Again, I'm not looking for a solution for where to put "location", I'm just trying to say that our requirements around the moderated content will quickly evolve. So can we have a solution that can evolve with us without needing to be redesigned every time?

I understand that we cannot have good universal UX for this case. But I think for this admin UI, flexibility of the design is more important than UX. A flexible design will allow us to move faster to improve the experience of end-users.

>The only problem I see here is that it appears randomly

@forabi a caching issue perhaps?

>I'd rather do it somewhat like this https://cl.ly/f409c783aab5
>
>Let me know what you think

For the implementation of the wireframes, we mostly rely on off-the-shelf components from [MUI](https://material-ui.com/).

The reason we use a menu instead of a drawer is because a menu provides an acceptable UX on both mobile and desktop. A drawer doesn't work well with our current design on desktop.

**Comment by forabi** [comment]
> The only problem I see here is that it appears randomly

> @forabi a caching issue perhaps?

I don't think it's a caching issue. @maxsnitser can you tell me exactly what you mean?

**Comment by mxsntsr** [comment]
Hi guys,

@wholesomedev 
I think there is no universal solution for the card that will work with data of different types. Of course, you can try stacking everything one after another. Imagine you have rows of data in the card. These are the rows that we currently have on cards now: 
Row 1. Name (title);
Row 2. Content (quote text / description);
Row 3. Source;
Row 4. User photo and name;
Row 5. Action buttons;

I think you can simply add more rows like Location and Comments. So, each row is a module. And you can move stuff around (change order of modules, etc). But it's a very raw approach... easy from the technical point of view, but could be hard to consume for users. Since in the long run, the data you put on cards could be overwhelming and there will be the point you'll need to manage it somehow by creating more views, filters, controls or other details etc.

So I'd say it's okay for now as an MVP solution, but maybe in the future, you'll need to work on details.

@forabi Nevermind regarding the menu. It's not critical at this stage. My point was about having it appear under the header, so the menu is not overlapping the header.

**Comment by wholesomedev** [comment]
@maxsnitser

Thanks for explaining. I think I agree with the majority of what you said 😃

@forabi

I think it might make more sense for us to go with the stacked rows approach for the time being, but I’m okay if you prefer the other way

**Comment by forabi** [comment]
Okay, since the stacked rows are more flexible, I think we should go with
that approach. 👍

**Comment by mxsntsr** [comment]
Sounds great! Do you, guys need anything else from me at this point?

**Comment by wholesomedev** [comment]
@maxsnitser I think with regard to the Admin UI, we are good at this time (unless @forabi has something else?)

I'll ping you again for new pages. Thanks a lot for your help with this! 😃

**Comment by mxsntsr** [comment]
Ok, got it. Thanks for the feedback, @wholesomedev

**Comment by forabi** [comment]
@wholesomedev @maxsnitser I don't have further comments on the UX. Thanks Max!
