### ISSUE TITLE
Using Docker

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#74]
I'm just starting my research on Docker, and I have a few thoughts on how we might be able to utilize it. Please correct me if I've got anything wrong.

---

The way I see it, we need two separate Docker images for Hollowverse:

### Env image

This image has the environment that can run Hollowverse. We can use the [Node container repo](https://hub.docker.com/_/node/) for that and add our own configurations like the Google Cloud command line tools. We can build and store it on Docker Hub. We can then publish updates to it if we need.

On Travis CI, we download this image for every build and spin up a new container from it. Then we use `docker exec` to execute commands inside this container—like `git clone`, `yarn install`, and `yarn test`.

### Prod image

This image also relies on the **Env image** but because it is a production container, it needs to be ready to go to work immediately. It shouldn't have an initialization step. So it should be ready to spin up the Hollowverse web server immediately upon running. That means we'll have to check-in our latest code in this image every time we build it. 

We'll have to think more about how to use Docker for production deployment if we want to do that.

## Next steps

If this sounds good, I can go ahead and create the `hollowverseEnv` Docker repo and publish it to Docker Hub. Then I can setup our Travis CI job to use that image instead of the Travis environment, which would alleviate the pain of getting Travis CI environment right.

Then I can also use the `hollowverseEnv` with the Google Cloud command line tool to deploy Release Manager from the CI to Google Cloud.

**Comment by levsthings** [comment]
The approach is spot on about the execution details, let's start with the **Env image** and start spinning it. You can share the dockerfile when it's ready and I'll take a look. The **Prod image** will be a bit more tricky but the main principles will be similar.

**Comment by wholesomedev** [comment]
Great. Okay, so this needs to be done before I can close #65 but it's not an immediate blocker. I'll continue to build Release Manager and when the time comes to have a proper deployment process for Release Manager, I'll work on the **Env image**.

**Comment by levsthings** [comment]
Sounds good to me!

**Comment by forabi** [comment]
This is for future reference: https://blog.alexellis.io/mutli-stage-docker-builds/

**Comment by forabi** [comment]
I don't think this issue is still relevant.

It seems to me that having two images is not really suitable for our use case. Environment images are usually used for compiled languages as they usually have two separate processes:

* Building: this needs an environment with all the tooling needed to compile the project.
* Running: this does not need any of the build environment tools as the compiled binaries do not depend on a runtime and can be executed immediately.

Things are different for Node.js projects:
* Our code does not need a compilation step (not considering TS code)
* We still need Node.js (and almost all of our dependencies) to be installed in our production environment.

Our current Dockerfile installs all the required Node.js modules and builds the client so most of our build steps are performed as part of the image build process. The servers are ready to start immediately after pulling the image.

As for the registry, we don't really need to have our images in the Docker registry as App Engine takes care of building the image and storing it in our private Google Container Registry (GCR).

**Comment by wholesomedev** [comment]
Yeah, sure. The main goal of this issue was to get a discussion going about using Docker. At the time Docker was a foreign concept to me and wanted to explore it. Now that we've actually started using Docker, we can close this one out.
